apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: httpd-frontend
  namespace: my-first-app
  labels:
    app: httpd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - image: registry.redhat.io/rhscl/httpd-24-rhel7:2.4-214
        imagePullPolicy: Always
        name: httpd-rhel7
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        resources:
          limits: 
            cpu: 500m
            memory: 1G
          requests:
            cpu: 200m
            memory: 512M
