---
- name: Launch AWS EC2 Instance
  hosts: localhost
  gather_facts: no

  vars:
    vpc_cidr_block: 10.0.0.0/16  
    vpc_name: my_vpc   
    key_name: ocp
    location: ap-southeast-2
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ location }}"   
        state: present
      register: vpc

    - name: Create security group
      amazon.aws.ec2_group:
        name: web-sg
        description: Ansible created security group
        region: "{{ location }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        vpc_subnet_id: subnet-0ba7a18fe253c80ec
        instance_type: t2.micro
        image_id: ami-0808460885ff81045
        region: "{{ location }}"
        security_group: web-sg
        network:
          assign_public_ip: true
        state: running
        count: 2
        tags:
          Env: "challenge"
      register: ec2
