apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-applications
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-project
  source:
    path: Cluster/dev-cluster/applications
    repoURL: https://github.com/ribua/kube.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
