clusters:
 - {}

applications:
  - name: webapp
    namespace: webapp
    argocdProject: cluster-project
    repo: https://github.com/ribua/kube.git
    path: Cluster/dev-cluster/applications/webapp
    targetRevision: master
    api: https://kubernetes.default.svc

  - name: namespace-users
    namespace: default
    argocdProject: namespace-users
    repo: https://github.com/ribua/kube.git
    path: Cluster/dev-cluster/namespaces
    targetRevision: master
    api: https://kubernetes.default.svc

