namespace: openshift-gitops


clusters:
 - {}

applications:
  - name: webapp
    namespace: webapp
    argocdProject: cluster-project
    repo: https://github.com/ribua/kube.git
    path: Cluster/dev-cluster/applications/webapp
    targetRevision: master
    api: https://kubernetes.default.svc

