apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: registry.redhat.io/rhscl/httpd-24-rhel7:2.4-212
        ports:
        - containerPort: 80
